data_sites:
  saber_11_2020_1:
    url: https://www.datos.gov.co/resource/a8xr-en99.json?
    url_main_page: https://www.datos.gov.co/Educaci-n/Saber-11-2020-1/a8xr-en99
  saber_11_2020_2:
    url: https://www.datos.gov.co/resource/rnvb-vnyh.json?
    url_main_page: https://www.datos.gov.co/Educaci-n/Saber-11-2020-2/rnvb-vnyh

